// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using ParentalControlApp.Models;

namespace ParentalControlApp.DB;

public partial class ParentalControlDBContext : DbContext
{
    public ParentalControlDBContext(DbContextOptions<ParentalControlDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ActivityLogs> ActivityLogs { get; set; }

    public virtual DbSet<BlockedApps> BlockedApps { get; set; }

    public virtual DbSet<Rules> Rules { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ActivityLogs>(entity =>
        {
            entity.HasKey(e => e.log_id).HasName("PK__Activity__9E2397E0322A6868");

            entity.Property(e => e.log_id).ValueGeneratedNever();
            entity.Property(e => e.timestamp).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.user).WithMany(p => p.ActivityLogs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ActivityL__user___6477ECF3");
        });

        modelBuilder.Entity<BlockedApps>(entity =>
        {
            entity.HasKey(e => e.app_id).HasName("PK__BlockedA__6F8A0A34139BA0DF");

            entity.Property(e => e.app_id).ValueGeneratedNever();

            entity.HasOne(d => d.user).WithMany(p => p.BlockedApps)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__BlockedAp__user___6754599E");
        });

        modelBuilder.Entity<Rules>(entity =>
        {
            entity.HasKey(e => e.rule_id).HasName("PK__Rules__E92A92964370F452");

            entity.Property(e => e.rule_id).ValueGeneratedNever();

            entity.HasOne(d => d.user).WithMany(p => p.Rules)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Rules__user_id__60A75C0F");
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasKey(e => e.user_id).HasName("PK__Users__B9BE370F6F4E6EC8");

            entity.Property(e => e.user_id).ValueGeneratedNever();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}