// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ParentalControlApp.Models;

public partial class ActivityLogs
{
    [Key]
    public Guid log_id { get; set; }

    public Guid user_id { get; set; }

    [Required]
    [StringLength(255)]
    public string action { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? timestamp { get; set; }

    [ForeignKey("user_id")]
    [InverseProperty("ActivityLogs")]
    public virtual Users user { get; set; }
}