// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ParentalControlApp.Models;

public partial class BlockedApps
{
    [Key]
    public Guid app_id { get; set; }

    public Guid user_id { get; set; }

    [Required]
    [StringLength(100)]
    public string app_name { get; set; }

    [ForeignKey("user_id")]
    [InverseProperty("BlockedApps")]
    public virtual Users user { get; set; }
}