// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ParentalControlApp.Models;

public partial class Rules
{
    [Key]
    public Guid rule_id { get; set; }

    public Guid user_id { get; set; }

    [Required]
    [StringLength(50)]
    public string rule_type { get; set; }

    [Required]
    [StringLength(100)]
    public string rule_value { get; set; }

    [ForeignKey("user_id")]
    [InverseProperty("Rules")]
    public virtual Users user { get; set; }
}