// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ParentalControlApp.Models;

[Index("username", Name = "UQ__Users__F3DBC57209BBE664", IsUnique = true)]
public partial class Users
{
    [Key]
    public Guid user_id { get; set; }

    [Required]
    [StringLength(50)]
    public string username { get; set; }

    [Required]
    [StringLength(255)]
    public string password { get; set; }

    [Required]
    [StringLength(10)]
    public string role { get; set; }

    [InverseProperty("user")]
    public virtual ICollection<ActivityLogs> ActivityLogs { get; set; } = new List<ActivityLogs>();

    [InverseProperty("user")]
    public virtual ICollection<BlockedApps> BlockedApps { get; set; } = new List<BlockedApps>();

    [InverseProperty("user")]
    public virtual ICollection<Rules> Rules { get; set; } = new List<Rules>();
}